// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/YasukeXXX/clean_architecture_go/controllers"
	"github.com/YasukeXXX/clean_architecture_go/infrastructures/memory"
	"github.com/YasukeXXX/clean_architecture_go/interactors"
	"github.com/YasukeXXX/clean_architecture_go/presenters/user"
)

// Injectors from wire.go:

func NewUserController() controllers.UserController {
	consolePresenter := presenters.NewConsolePresenter()
	userRepository := memory.NewUserRepository()
	userInteractor := interactors.NewUserInteractor(consolePresenter, userRepository)
	userController := controllers.NewUserController(userInteractor)
	return userController
}
